import {
	Selector
} from 'testcafe'

export default class Page {
	constructor() {

		this.pageURLs = [
			this.allyLiveStarting = 'https://tradertoolkit.efxnow.com/Live/US/EN/Auth/SignIn?vn=alfxg2&voea=2343&uid=12345',
			this.allyLive = 'https://tradertoolkit.efxnow.com/Live/US/EN/News',
			this.allyDemoStarting = 'https://tradertoolkit.efxnow.com/Demo/US/EN/Auth/SignIn?vn=alfxg2&voea=333&uid=12345',
			this.allyDemo = 'https://tradertoolkit.efxnow.com/Demo/US/EN/News',
			this.caLiveStarting = 'https://tradertoolkit.efxnow.com/Live/CA/EN/Auth/SignIn?vn=fcc&voea=2123&uid=12345',
			this.caDemoStarting = 'https://tradertoolkit.efxnow.com/Demo/CA/EN/Auth/SignIn?vn=fcc&voea=2123&uid=12345',
			this.caLive = 'https://tradertoolkit.efxnow.com/Live/CA/EN/ForexInsider',
			this.caDemo = 'https://tradertoolkit.efxnow.com/Demo/CA/EN/ForexInsider',
			this.cimaENLiveStarting = 'http://tradertoolkit.qatest.local/Live/UK/EN/Auth/SignIn?vn=gccig2&voea=2332&uid=12345',
			this.cimaDemoStarting = 'http://tradertoolkit.qatest.local/Demo/UK/EN/Auth/SignIn?vn=gccig2&voea=2332&uid=12345',
			this.cimaENLive = 'http://tradertoolkit.qatest.local/Live/UK/EN/News',
			this.cimaENDemo = 'http://tradertoolkit.qatest.local/Demo/UK/EN/News',
			this.startingUKENLive = 'https://tradertoolkit.efxnow.com/Live/UK/EN/Auth/SignIn?vn=fcukg2&voea=1231&uid=12345',
			this.startingUKENDemo = 'https://tradertoolkit.efxnow.com/DEMO/UK/EN/Auth/SignIn?vn=fcukg2&voea=1231&uid=12345',
			this.liveUKEN = 'https://tradertoolkit.efxnow.com/Live/UK/EN/ForexInsider',
			this.demoUKEN = 'https://tradertoolkit.efxnow.com/DEMO/UK/EN/ForexInsider',
			this.startingUSENLive = 'https://tradertoolkit.efxnow.com/Live/US/EN/Auth/SignIn?vn=fcg2us&voea=123&uid=12345',
			this.startingUSENDemo = 'https://tradertoolkit.efxnow.com/Demo/US/EN/Auth/SignIn?vn=fcg2us&voea=123&uid=12345',
			this.liveUSEN = 'https://tradertoolkit.efxnow.com/Live/US/EN/News',
			this.demoUSEN = 'https://tradertoolkit.efxnow.com/Demo/US/EN/ForexInsider'

];

		this.pageElements = [
      		this.pageTitle = Selector('title'),
			this.tradeIdeas = Selector('#li1 > span'),
			this.tradeIdeasAutoChartist = Selector('#li_tradeIdeas > span > a'),
			this.techAnalysis = Selector('#li2 > span'),
			this.autoChartPatterns = Selector('#li2 > ul > li:nth-child(1) > span > a'),
			this.tcTechAnalysis = Selector('#li_tafromtradecentral > span > a'),
			this.techUpdate = Selector('#li_technicalUpdate > span > a'),
			this.commentary = Selector('#li4 > span'),
			this.forexInsider = Selector('#li_forexInsider > span > a'),
			this.forexTweets = Selector('#li_microblogging > span > a'),
			this.fundamentalAnalysis = Selector('#li5 > span'),
			this.calendar = Selector('#li5 > ul > li:nth-child(1) > span > a'),
			this.latestResearch = Selector('#li_latestResearch > span > a'),
			this.news = Selector('#li_news > span > a'),
			this.researchReports = Selector('#li_researchReports > span > a'),
			this.funds = Selector('#li6 > span'),
			this.deposit = Selector('#li6 > ul > li:nth-child(1) > span > a'),
			this.withdraw = Selector('#li6 > ul > li:nth-child(2) > span > a'),
			this.transfer = Selector('#li6 > ul > li.last > span > a'),
			this.profile = Selector('#li7 > span'),
			this.rolloverRates = Selector('#li_rolloverRates > span > a'),
			this.transactionDataReport = Selector('#li7 > ul > li:nth-child(2) > span > a'),
			this.costPerTradeReport = Selector('#li_costPerTradeReport > span > a'),
			this.support = Selector('#li8 > span'),
			this.liveChat = Selector('#li8 > ul > li:nth-child(1) > span > a'),
			this.contactInfo = Selector('#li8 > ul > li.last > span > a'),
			this.contactInfoCA = Selector('#li8 > ul > li:nth-child(2) > span > a'),
			this.liveChatHeader = Selector('#toplinks > span > a'),
			this.imageHeader = Selector('#logoMain'),
			this.eaHosting = Selector('#li7 > ul > li:nth-child(1) > span > a'),
			this.updateAccountProfile = Selector('#li7 > ul > li:nth-child(2) > span > a'),
			this.linkAccounts = Selector('#li7 > ul > li:nth-child(3) > span > a'),
			this.annualCustState = Selector('#li_annualCustomerStatement > span > a'),
			this.cfdProductDetails = Selector('#li_cfdProductDetails > span > a'),
			this.cfdProductDetailsCimaEN = Selector('#li8 > ul > li.last > span > a'),
			this.marginChangeRequest = Selector('#li7 > ul > li:nth-child(2) > span > a'),
			this.updateAccountProfileCA = Selector('#li7 > ul > li:nth-child(3) > span > a'),
			this.updateAccountProfileUKEN = Selector('#li7 > ul > li:nth-child(1) > span > a'),
			this.linkAccountsCADemo = Selector('#li7 > ul > li:nth-child(4) > span > a'),
			this.rolloverRatesDemoCA = Selector('#li_rolloverRates > span > a')


];

		this.pageData = [
      		this.homePageTitleNews = 'News',
			this.homePageTitleForexInsider = 'FOREXInsider',
			this.tradeIdeasText = 'Trade Ideas',
			this.tradeIdeasAutoChartistText = 'Autochartist - Trade Ideas',
			this.techAnalysisText = 'Technical Analysis',
			this.autoChartPatternsText = 'Autochartist - Chart Patterns',
			this.tcTechAnalysisText = 'Trading Central – Technical Analysis',
			this.techUpdateText = 'Technical Update',
			this.commentaryText = 'Commentary',
			this.forexInsiderText = 'FOREXInsider',
			this.forexTweetsText = '@FOREXcomTweets',
			this.fundamentalAnalysisText = 'Fundamental Analysis',
			this.calendarText = 'Calendar',
			this.latestResearchText = 'Latest Research',
			this.newsText = 'News',
			this.researchReportsText = 'Research Reports',
			this.fundsText = 'Funds',
			this.depositText = 'Deposit',
			this.withdrawText = 'Withdraw',
			this.transferText = 'Transfer',
			this.profileText = 'Profile',
			this.rolloverRatesText = 'Rollover Rates',
			this.transactionDataReportText = 'Transaction Data Report',
			this.costPerTradeReportText = 'Cost per Trade Report',
			this.supportText = 'Support',
			this.liveChatText = 'Live Chat',
			this.contactInfoText = 'Contact Info',
			this.eaHostingText = 'EA Hosting Sign-Up',
			this.updateAccountProfileText = 'Update Account Profile',
			this.linkAccountsText = 'Link Accounts',
			this.annualCustStateText = 'Annual Customer Statement',
			this.cfdProductDetailsText = 'CFD Product Details',
			this.marginChangeRequestText = 'Request a Margin Change'
];

		this.pageOutURLs = [
			this.calendarURL = 'http://secure.efxnow.com/UtilityPresentation/Default.aspx?UID=1051005&Language=ENG',
			this.calendarHttpsURL = 'https://secure.efxnow.com/UtilityPresentation/Default.aspx?UID=1051005&Language=ENG',
			this.tradeIdeasAutoChartistURL = '/Live/CA/EN/TradeIdeas',
			this.tradeIdeasAutoChartistURLDemo = '/Demo/CA/EN/TradeIdeas',
			this.tradeIdeasAutoChartistCimaENURL = '/Live/UK/EN/TradeIdeas',
			this.tradeIdeasAutoChartistCimaENURLDemo = '/Demo/UK/EN/TradeIdeas',
			this.tradeIdeasAutoChartistUKENURLDemo = '/DEMO/UK/EN/TradeIdeas',
			this.tradeIdeasAutoChartistURLUS = '/Live/US/EN/TradeIdeas',
			this.tradeIdeasAutoChartistURLUSDemo = '/Demo/US/EN/TradeIdeas',
			this.autoChartPatternsURL = 'http://gain.autochartist.com/aclite/GainCapitalCFDMain?username=12345&accountType=0',
			this.autoChartPatternsURLDemo = 'http://gain.autochartist.com/aclite/GainCapitalCFDMain?username=12345&accountType=1',
			this.autoChartPatternsUSURL = 'http://gain.autochartist.com/aclite/GainCapitalMain?username=12345&accountType=0',
			this.autoChartPatternsUSURLDemo = 'http://gain.autochartist.com/aclite/GainCapitalMain?username=12345&accountType=1',
			this.tcTechAnalysisURL = '/Live/CA/EN/TradingCentral',
			this.tcTechAnalysisURLDemo = '/Demo/CA/EN/TradingCentral',
			this.tcTechAnalysisCimaENURL = '/Live/UK/EN/TradingCentral',
			this.tcTechAnalysisCimaENURLDemo = '/Demo/UK/EN/TradingCentral',
			this.techUpdateURL = '/Live/CA/EN/TechnicalUpdate',
			this.techUpdateURLDemo = '/Demo/CA/EN/TechnicalUpdate',
			this.forexInsiderURL = '/Live/CA/EN/ForexInsider',
			this.forexInsiderURLDemo = '/Demo/CA/EN/ForexInsider',
			this.forexInsiderUKENURL = '/Live/UK/EN/ForexInsider',
			this.forexInsiderUKENURLDemo = '/DEMO/UK/EN/ForexInsider',
			this.forexInsiderUSURLDemo = '/Demo/US/EN/ForexInsider',
			this.forexTweetsURL = '/Live/CA/EN/Microblogging',
			this.forexTweetsURLDemo = '/Demo/CA/EN/Microblogging',
			this.forexTweetsCimaENURL = '/Live/UK/EN/Microblogging',
			this.forexTweetsCimaENURLDemo = '/Demo/UK/EN/Microblogging',
			this.forexTweetsUKENURLDemo = '/DEMO/UK/EN/Microblogging',
			this.forexTweetsUSURL = '/Live/US/EN/Microblogging',
			this.forexTweetsUSURLDemo = '/Demo/US/EN/Microblogging',
			this.latestResearchURL = '/Live/US/EN/LatestResearch',
			this.latestResearchURLDemo = '/Demo/US/EN/LatestResearch',
			this.latestResearchURLCA = '/Live/CA/EN/LatestResearch',
			this.latestResearchURLCADemo = '/Demo/CA/EN/LatestResearch',
			this.latestResearchURLCimaEN = '/Live/UK/EN/LatestResearch',
			this.latestResearchURLCimaENDemo = '/Demo/UK/EN/LatestResearch',
			this.newsURL = '/Live/US/EN/News',
			this.newsURLDemo = '/Demo/US/EN/News',
			this.newsURLCA = '/Live/CA/EN/News',
			this.newsURLCADemo = '/Demo/CA/EN/News',
			this.newsURLCimaEN = '/Live/UK/EN/News',
			this.newsURLCimaENDemo = '/Demo/UK/EN/News',
			this.newsURLUKENDemo = '/DEMO/UK/EN/News',
			this.researchReportsURL = '/Live/US/EN/ResearchReports',
			this.researchReportsURLDemo = '/Demo/US/EN/ResearchReports',
			this.researchReportsURLCA = '/Live/CA/EN/ResearchReports',
			this.researchReportsURLCADemo = '/Demo/CA/EN/ResearchReports',
			this.depositURLAlly = 'https://account.efxnow.com/login/ally?ReturnUrl=/funding/deposit/cards',
			this.depositURLCA = 'https://myaccount.forex.com/index.html?docId=funding&lang=English',
			this.depositURLUKEN = 'https://account.efxnow.com/login/forexuken?culture=en-GB &returnurl=/funding/deposit/cards',
			this.withdrawURLUKEN = 'https://account.efxnow.com/login/forexuken?culture=en-GB&returnurl=/funding/withdrawal/cards',
			this.withdrawURLAlly = 'https://account.efxnow.com/login/ally?ReturnUrl=/funding/withdrawal/cards',
			this.depositURLCimaEN = 'https://account.forex.com/funding/deposit/card',
			this.withdrawURLCA = 'https://myaccount.forex.com/index.html?amp;docId=withdraw&lang=English',
			this.withdrawURLCimaEN = 'https://account.forex.com/funding/withdrawal/cards',
			this.depositURLUS = 'https://account.forex.com/account/login',
			this.withdrawURLSUS = 'https://account.forex.com/account/login',
			this.transferURLUS = 'https://account.forex.com/account/login',
			this.transferURLAlly = 'https://account.efxnow.com/login/ally',
			this.transferURLCA = 'https://myaccount.forex.com/index.html?amp;docId=withdraw&lang=English',
			this.rolloverRatesURL = '/Live/US/EN/RolloverRates',
			this.rolloverRatesURLDemo = '/Demo/US/EN/RolloverRates',
			this.rolloverRatesURLCA = '/Live/CA/EN/RolloverRates',
			this.rolloverRatesURLCADemo = '/Demo/CA/EN/RolloverRates',
			this.rolloverRatesCimaENURL = '/Live/UK/EN/RolloverRates',
			this.rolloverRatesCimaENURLDemo = '/Demo/UK/EN/RolloverRates',
			this.rolloverRatesUKENURLDemo = '/DEMO/UK/EN/RolloverRates',
			this.rolloverRatesURLUSLive = '/Live/US/EN/RolloverRates',
			this.rolloverRatesURLUSDemo = '/Demo/US/EN/RolloverRates',
			this.transactionDataReportURLAlly = 'https://invest.ally.com/forex/risk_warning.htm',
			this.costPerTradeReportURL = '/Live/US/EN/CostPerTradeReport',
			this.liveChatURLAlly = 'https://z1.liveper.sn/api/account/21749759/route/campaign/298724314/engagement/298745014',
			this.liveChatURLCA = 'https://z1.liveper.sn/api/account/21749759/route/campaign/233271714/engagement/242396014',
			this.liveChatURLCADemo = 'https://z1.liveper.sn/api/account/21749759/route/campaign/233271714/engagement/242395914',
			this.liveChatURLCimaEN = 'https://z1.liveper.sn/api/account/21749759/route/campaign/265616214/engagement/265617614',
			this.liveChatURLUKENLive = 'https://z1.liveper.sn/api/account/21749759/route/campaign/248537714/engagement/248538614',
			this.liveChatURLUKENDemo = 'https://z1.liveper.sn/api/account/21749759/route/campaign/248537714/engagement/248539114',
			this.liveChatURLUSLive = 'https://www.forex.com/en-us/support?lp_offsite=%7B%22type%22%3A0%2C%22campaignId%22%3A248667014%2C%22engagementId%22%3A248668014%2C%22contextId%22%3A%221755603c-b0c8-494c-918e-683540209338%22%2C%22accountId%22%3A%2221749759%22%2C%22webView%22%3Afalse%7D',
			this.liveChatURLUSDemo = 'http://server.iad.liveperson.net/hc/75190831/?cmd=file&file=visitorWantsToChat&site=75190831&byhref=1',
			this.contactInfoURLAlly = 'https://invest.ally.com/forex/contact_us.htm',
			this.contactInfoURLCA = 'http://forex.com/ca/support.html',
			this.contactInfoURLCADemo = 'http://www.forex.com/ca/support.html',
			this.contactInfoURLCimaEN = 'https://www.forex.com/en/support/',
			this.contactInfoURLUKEN = 'https://www.forex.com/en-uk/support',
			this.contactInfoURLUS = 'https://www.forex.com/en-us/support',
			this.contactInfoURLUSDemo = 'http://www.forex.com/support.html',
			this.imageHeaderAlly = '/css/ally/_default/_default/_default/images/forex_logo.png',
			this.allyDemoOLS = 'https://application.efxnow.com/ally-en-us-meta/step/1',
			this.cimaENDemoOLS = 'https://application.forex.com/en-meta/step/1',
			this.caDemoOLS = 'https://secure.efxnow.com/NewOLS_GCCA_EN/applyforex.aspx?&bc=mqca&ibc=gcca&sibc=mqca',
			this.eaHostingURLCA = 'http://www.forex.com/ca/trading-platforms/metatrader/ea-hosting.html',
			this.eaHostingLiveCimaEN = 'https://www.forex.com/en/services/trading-platforms/metatrader/expert-advisors',
			this.eaHostingURLUKEN = 'https://www.forex.com/en-uk/trading-platforms/metatrader/expert-advisors',
			this.eaHostingURLUS = 'https://www.forex.com/en-us/trading-platforms/metatrader',
			this.updateAccountProfileURLCA = 'https://myaccount.forex.com/index.html?amp;docId=withdraw&lang=English',
			this.updateAccountProfileURLCimaEN = 'https://account.forex.com/account/settings/profile',
			this.updateAccountProfileURLUKEN = 'https://account.forex.com/login/forexuken',
			this.updateAccountProfileURLUS = 'https://account.forex.com/account/login',
			this.linkAccountsURLCA = 'https://myaccount.forex.com/index.html?amp;docId=withdraw&lang=English',
			this.annualCustStateCAURL = '/Live/CA/EN/AnnualCustomerStatement',
			this.cfdProductDetailsCA = '/Live/CA/EN/CFDProductDetails',
			this.cfdProductDetailsCADemo = '/Demo/CA/EN/CFDProductDetails',
			this.cfdProductDetailsURLCimaEN = 'https://www.forex.com/en/markets/pricing/',
			this.cfdProductDetailsURLUKEN = 'http://www.filesandimages.com/Brand/GAINCapital/PDF/CFDContractDetailsForexGFMetaEN.pdf',
			this.marginChangeRequestURL = '/Demo/CA/EN/ChangeMargin',
			this.ukENDEMOOLS = 'https://application.forex.com/en-uk-meta/step/1',
			this.usENDEMOOLS = 'https://application.forex.com/en-us-meta/step/1'
		];



	}
}
